name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r application/requirements.txt

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.CI_REGISTRY }}/my-app:${{ github.sha }} ./application
          echo ${{ secrets.CI_REGISTRY_KEY }} | docker login ${{ secrets.CI_REGISTRY }} --username builder --password-stdin
          docker push ${{ secrets.CI_REGISTRY }}/my-app:${{ github.sha }}
# команды для развертывания в тестовом окружении
  deploy-test-env:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to testing environment
        run: |
          
# команды для тестирования
  test:
    runs-on: ubuntu-latest
    needs: deploy-test-env
    steps:
      - name: Run tests
        run: |
          
# команды для удаления тестового окружения
  delete-test-env:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Delete testing environment
        run: |
          
# команды для развертывания в продакшн окружении
  release:
    runs-on: ubuntu-latest
    needs: delete-test-env
    steps:
      - name: Deploy to production
        run: |
